
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-01T21:16:20-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "32c00bc85c284791e9e55b74885b6825b9ef111e",
 "version": "1.0.0b5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
